tap_gui:
  #service_type: ClusterIP
  app_config:
  #  app:
  #    baseUrl: http://tap-gui.34.136.250.20.nip.io # No port needed with Ingress
    integrations:
      github: # Other integrations available see NOTE below
        - host: github.com
          token: YOUR_GITHUB_TOKEN
    catalog:
      locations:
        - type: url
          target: https://github.com/gabo1208/vmware-tap/blob/main/tap-gui/catalogs/blank/catalog-info.yaml
  #  backend:
    #  baseUrl: http://tap-gui.34.136.250.20.nip.io # No port needed with Ingress
    #  cors:
    #    origin: http://tap-gui.34.136.250.20.nip.io # No port needed with Ingress